# Generated by Django 5.1.2 on 2024-10-26 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lenguaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('expirencia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fechaIni', models.DateField()),
                ('fechaFin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('listProyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencia', to='pages.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('nivel', models.CharField(max_length=1)),
                ('imagen', models.ImageField(upload_to='portfolio/')),
                ('listHabilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='pages.habilidad')),
                ('listaExperiencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='pages.experiencia')),
                ('listaLenguaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='pages.lenguaje')),
                ('listaProyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='pages.proyecto')),
                ('listaSocial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='pages.social')),
                ('listaTrabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='pages.trabajo')),
            ],
        ),
    ]
